version: 2

jobs:
  build:
    working_directory: ~/circleci-infra-agent
    environment:
      LIBRARY: feedyard
      CONTAINER_NAME: circleci-infra-agent
      VERSION: 3.6

    docker:
      - image: feedyard/circleci-docker # replace with self once at testable version
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: 'docker info'
      - run:
          name: build image
          command: 'docker build -t $LIBRARY/$CONTAINER_NAME:latest .'
      - run:
          name: tag with build version
          command: 'docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM'
      - run:
          name: configuration tests
          command: |
            inspec exec profiles/cis-docker